pipeline {
    agent {
        docker {
            image 'node:lts-slim'
            args '-p 5050:5050'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mkdir -p node_modules/.npm'
                sh 'chmod -R 777 node_modules/.npm'
                sh 'npm install --loglevel=verbose'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
